### ISSUE TITLE
can't figure out how to decode a {[index: string]: Foo}

### ISSUE THREAD

**Issue by radix** [ooesili/type-safe-json-decoder#5]
The `object` function is very useful for decoding objects with specific keys, but I also have types which have arbitrary string keys, all of which have the same type of value.

In Elm I would use the `dict` function for this case, but I can't find anything similar in this library. Maybe it's possible using the combinators available? I haven't been able to figure out how, though.

**Comment by ooesili** [comment]
Thanks for bringing this up! I don't think there is a way with the existing library. I threw up [this branch](https://github.com/ooesili/type-safe-json-decoder/tree/wm/dict) with a port of the `dict` combinator.

I think the code is good, but I'm going to try to think about edge cases and maybe a better name tonight. `dict` maybe feels a little weird, since JavaScript doesn't really make that distinction, but `object` is already taken.

Some other ideas for a name are `index`, `stringIndex`, `anyKeys`. `dict` is honestly my favorite so far. I do think it conveys the meaning the best, and it mirrors the Elm library.

**Comment by radix** [comment]
I also like `dict` the best of the options you mentioned. I think to get more descriptive it would have to get more wordy, like `arbitraryKeyObject` or something. maybe `mapping`? eh.

Anyway, I'll give your branch a try (if I can figure out how to get my build system to use it :)

**Comment by radix** [comment]
yeah... so I can't figure out how to get this loading up in my project :P sorry, I'm a newbie to this ecosystem. I ran

```
npm5 install git://github.com/ooesili/type-safe-json-decoder#377fe8163a1e68c4a28fdd8d8b2c5d663342d8d5
```

to get your branch installed, and it seemed to work, but then typescript couldn't import the module (and of course, it could previously after I initially installed with just `npm5 install type-safe-json-decoder`). Do you know if I need to take another step to get the branch registered with the typescript compiler?

**Comment by ooesili** [comment]
I don't know if this is the simplest way but it worked for me. Clone the repo somewhere, checkout the `wm/dict` branch, then run `npm run build` inside the repo. That will create a `dist` folder, which is what I actually end up publishing as an npm package. Then from inside your project run `npm install /path/to/type-safe-json-decoder/dist`.

**Comment by radix** [comment]
It took some wrangling, but I eventually got it to work! Just some notes:

- `npm run build` doesn't work on Windows because your `build` script has some unix-isms (but I think that's just the status quo in npm-world)
- so I ran `tsc` manually and copied the files around until it worked. However, for some reason `tsc` couldn't build `spec/index-spec.ts` because it doesn't import `describe`, `it` etc. So I just ended up deleting the contents of that file

But I got it working, and tested the new `dict` function and it works great! Thanks :)

**Comment by radix** [comment]
Woops! I spoke too soon. There does seem to be a bug in the new `dict` function.

```
  assertEq(JD.dict(JD.map((x): string => "foo", JD.number())).decodeAny({key: 3}), {key: "foo"});
```

(with type-safe-json-mapper imported as `JD`) results in

```
Not equal {
  "key": 3
} !== {
  "key": "foo"
}
```

It looks like mapping in a decoder used in a dict isn't working -- it basically looks like it's returning the original input instead of the transformed output.

**Comment by radix** [comment]
ok, found the bug, just a simple `return obj` that should be `return result` in the dict function :)

**Comment by ooesili** [comment]
Oops. Just pushed up a fix and a test for that case.

**Comment by radix** [comment]
confirmed fixed :)

**Comment by ooesili** [comment]
Excellent! I just pushed up typedocs for the function. I also pulled this out of the function signature:
```typescript
export type Dict<T> = {[index: string]: T}
```
because TypeDoc generated this
```typescript
dict<T>(value: Decoder<T>): Decoder<object>
...
Returns Decoder<object>
```
which is kind of weird. With the `Dict` type pulled out and named it looks a little better
```typescript
dict<T>(value: Decoder<T>): Decoder<Dict>
...
Returns Decoder<Dict>
```
but at least you can find `Dict` and see this at some point
```typescript
Dict
...
Type declaration

[index: string]: T
```
There should be no difference from a code perspective, because of TypeScript's structural typing. The tests still run fine.

**Comment by radix** [comment]
looks good @ooesili. The documentation does look nicer that way, and I tested the changes with my code and it still works fine. Thanks for making this improvement :)

**Comment by ooesili** [comment]
Just pushed up v0.2.0 to npm!
